from __future__ import print_function, division
import matplotlib.pyplot as plt
import csv
import sys
import numpy as np
import pickle
import glob
import keras
import os
import click
from pathlib import Path
from tensorflow.keras import backend
from music21 import converter, instrument, note, chord, stream
from tensorflow.keras.layers import Input, Dense, Reshape, Dropout, LSTM, Bidirectional
from tensorflow.keras.layers import (
    BatchNormalization,
    Activation,
    ZeroPadding2D,
    LeakyReLU,
)
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.optimizers import Adam
from keras.utils import np_utils
from tensorflow.keras.utils import plot_model

# Returns note_to_emotion pairs
def read_note_from_file(filename, emotion):
    midi = converter.parse(filename)
    note_to_emotion = []
    print(f"Parsing label {emotion} for file {filename}...")

    notes_to_parse = None

    try:  # file has instrument parts
        s2 = instrument.partitionByInstrument(midi)
        notes_to_parse = s2.parts[0].recurse()
    except:  # file has notes in a flat structure
        notes_to_parse = midi.flat.notes

    for element in notes_to_parse:
        if isinstance(element, note.Note):
            note_to_emotion.append((str(element.pitch), emotion))
        elif isinstance(element, chord.Chord):
            note_to_emotion.append(
                (".".join(str(n) for n in element.normalOrder), emotion)
            )

    return note_to_emotion


def get_note_to_emotion(folder_path):
    """ Get all the notes and chords from the midi files """
    note_to_emotion = []
    file_name_to_emotion = {}
    class_list = []
    # parse file with emotions.
    for file in Path(folder_path).rglob("*.mid"):
        label = Path(file).parent.stem
        if label in class_list:
            index = class_list.index(label)
        else:
            class_list.append(label)
            index = class_list.index(label)
        file_name_to_emotion[file] = index

    # Read notes from files
    for file, emotion in file_name_to_emotion.items():
        note_to_emotion += read_note_from_file(file, emotion)

    return note_to_emotion, class_list


def prepare_sequences(note_to_emotion, n_vocab):
    """ Prepare the sequences used by the Neural Network """
    sequence_length = 100

    # Get all pitch names
    pitchnames = sorted(set(note for note, emotion in note_to_emotion))

    # Create a dictionary to map pitches to integers
    note_to_int = dict((note, number) for number, note in enumerate(pitchnames))

    network_input = []
    network_output = []

    # create input sequences and the corresponding outputs
    for i in range(0, len(note_to_emotion) - sequence_length, 1):
        sequence_in = note_to_emotion[i : i + sequence_length - 5]
        sequence_out = note_to_emotion[i + sequence_length][0]
        new_input = []
        for note, emotion in sequence_in:
            new_input.append(note_to_int[note])
        # append emotion
        for note, emotion in sequence_in[:5]:
            new_input.append(emotion)
        network_input.append(new_input)
        network_output.append(note_to_int[sequence_out])

    n_patterns = len(network_input)

    # Reshape the input into a format compatible with LSTM layers
    network_input = np.reshape(network_input, (n_patterns, sequence_length, 1))

    # Normalize input between -1 and 1
    network_input = (network_input - float(n_vocab) / 2) / (float(n_vocab) / 2)
    network_output = np_utils.to_categorical(network_output)

    return (network_input, network_output)


def create_midi(prediction_output, filename):
    """convert the output from the prediction to notes and create a midi file
    from the notes"""
    offset = 0
    output_notes = []

    # create note and chord objects based on the values generated by the model
    for item in prediction_output:
        pattern = item[0]
        # pattern is a chord
        if ("." in pattern) or pattern.isdigit():
            notes_in_chord = pattern.split(".")
            notes = []
            for current_note in notes_in_chord:
                new_note = note.Note(int(current_note))
                new_note.storedInstrument = instrument.Piano()
                notes.append(new_note)
            new_chord = chord.Chord(notes)
            new_chord.offset = offset
            output_notes.append(new_chord)
        # pattern is a note
        else:
            new_note = note.Note(pattern)
            new_note.offset = offset
            new_note.storedInstrument = instrument.Piano()
            output_notes.append(new_note)

        # increase offset each iteration so that notes do not stack
        offset += 0.5

    midi_stream = stream.Stream(output_notes)
    midi_stream.write("midi", fp="{}.mid".format(filename))
    return output_notes


class GAN:
    def __init__(self, data_path, seq_length, latent_dim=1000, lr=0.0002):
        self.seq_length = seq_length
        self.seq_shape = (self.seq_length, 1)
        self.latent_dim = latent_dim
        self.disc_loss = []
        self.gen_loss = []

        # note and emotion sets
        self.note_to_emotion, self.class_list = get_note_to_emotion(data_path)
        self.num_emotion = len(self.class_list)

        optimizer = Adam(lr, 0.5)

        # Build and compile the discriminator
        self.discriminator = self.build_discriminator()
        self.discriminator.compile(
            loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"]
        )

        # Build the generator
        self.generator = self.build_generator()

        # The generator takes noise as input and generates note sequences
        z = Input(shape=self.seq_shape)
        generated_seq = self.generator(z)

        # For the combined model we will only train the generator
        self.discriminator.trainable = False

        # The discriminator takes generated images as input and determines validity
        validity = self.discriminator(generated_seq)

        # The combined model  (stacked generator and discriminator)
        # Trains the generator to fool the discriminator
        self.combined = Model(z, validity)
        self.combined.compile(loss="binary_crossentropy", optimizer=optimizer)

    def get_generator(self):
        return self.generator

    def build_discriminator(self):

        model = Sequential()
        model.add(LSTM(512, input_shape=self.seq_shape, return_sequences=True))
        model.add(Bidirectional(LSTM(512)))
        model.add(Dense(512))
        model.add(LeakyReLU(alpha=0.2))
        model.add(Dense(256))
        model.add(LeakyReLU(alpha=0.2))
        model.add(Dense(1, activation="sigmoid"))
        model.summary()
        plot_model(
            model,
            to_file="discriminator_plot.png",
            show_shapes=True,
            show_layer_names=True,
        )
        seq = Input(shape=self.seq_shape)
        validity = model(seq)

        return Model(seq, validity)

    def build_generator(self):

        model = Sequential()
        model.add(LSTM(256, input_shape=self.seq_shape, return_sequences=True))
        model.add(Bidirectional(LSTM(256)))
        model.add(Dense(256))
        model.add(LeakyReLU(alpha=0.2))
        model.add(BatchNormalization(momentum=0.8))
        model.add(Dense(512))
        model.add(LeakyReLU(alpha=0.2))
        model.add(BatchNormalization(momentum=0.8))
        model.add(Dense(1024))
        model.add(LeakyReLU(alpha=0.2))
        model.add(BatchNormalization(momentum=0.8))
        model.add(Dense(np.prod(self.seq_shape), activation="tanh"))
        model.add(Reshape(self.seq_shape))
        model.summary()
        plot_model(
            model, to_file="generator_plot.png", show_shapes=True, show_layer_names=True
        )

        noise = Input(shape=self.seq_shape)
        seq = model(noise)

        return Model(noise, seq)

    def train(
        self,
        epochs,
        batch_size=128,
        print_interval=50,
        save_interval=1000,
        exp_path="results",
    ):

        # Load and convert the data
        n_vocab = len(set([note for note, emotion in self.note_to_emotion]))
        X_train, y_train = prepare_sequences(self.note_to_emotion, n_vocab)
        print("vocab_sizes: ", n_vocab)
        print("X_train: ", X_train.shape)
        print("batch size: ", batch_size)

        # Adversarial ground truths
        real = np.ones((batch_size, 1))
        fake = np.zeros((batch_size, 1))

        # Training the model
        for epoch in range(epochs):

            # Training the discriminator
            # Select a random batch of note sequences
            idx = np.random.randint(0, X_train.shape[0], batch_size)
            real_seqs = X_train[idx]

            # noise = np.random.choice(range(484), (batch_size, self.latent_dim))
            # noise = (noise-242)/242
            noise = np.random.normal(
                0, 1, (batch_size, self.seq_shape[0], self.seq_shape[1])
            )
            # Generate a batch of new note sequences
            gen_seqs = self.generator.predict(noise)

            # Train the discriminator
            d_loss_real = self.discriminator.train_on_batch(real_seqs, real)
            d_loss_fake = self.discriminator.train_on_batch(gen_seqs, fake)
            d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

            #  Training the Generator
            noise = np.random.normal(
                0, 1, (batch_size, self.seq_shape[0], self.seq_shape[1])
            )

            # Train the generator (to have the discriminator label samples as real)
            g_loss = self.combined.train_on_batch(noise, real)

            # Print the progress and save into loss lists
            if epoch % print_interval == 0:
                print(
                    "%d [D loss: %f, acc.: %.2f%%] [G loss: %f]"
                    % (epoch, d_loss[0], 100 * d_loss[1], g_loss)
                )
                self.disc_loss.append(d_loss[0])
                self.gen_loss.append(g_loss)

            if epoch % save_interval == 0:
                # save the generator model
                self.generator.save_weights("cgan_generator.h5")
                self.plot_loss()
                # generate samples
                for i in range(10):
                    for j in range(4):
                        self.generate(exp_path, j + 1, i + 1)

    def generate(self, exp_path, emotion, out_index):
        # Get pitch names and store in a dictionary
        pitchnames = sorted(set(note for note, emotion in self.note_to_emotion))
        # Create a dictionary to map pitches to integers
        int_to_note = dict((number, note) for number, note in enumerate(pitchnames))
        # Use random noise to generate sequences
        music_noise = np.random.normal(
            0, 1, (1, self.seq_shape[0] - 10, self.seq_shape[1])
        )
        emotion_noise = np.ones((1, 10, self.seq_shape[1])) * emotion
        noise = np.concatenate((music_noise, emotion_noise), axis=1)
        predictions = self.generator.predict(noise)

        pred_notes = [
            x * len(pitchnames) / 2 + len(pitchnames) / 2 - 0.5 for x in predictions[0]
        ]
        pred_notes = [int_to_note[int(x)] for x in pred_notes]

        filename = Path(exp_path) / (
            "gan_generated_{self.class_list[emotion]}_{out_index}"
        )

        return create_midi(pred_notes, filename)

    def plot_loss(self):
        plt.plot(self.disc_loss, c="red")
        plt.plot(self.gen_loss, c="blue")
        plt.title("GAN Loss per Epoch")
        plt.legend(["Discriminator", "Generator"])
        plt.xlabel("Epoch")
        plt.ylabel("Loss")
        plt.savefig("GAN_Loss_per_Epoch_final.png", transparent=True)
        plt.close()


@click.command()
@click.option("--exp_path", default="results", help="AAA")
@click.option("--data_path", default="../data", help="AAA")
@click.option("--seq_length", default=100, help="AAA")
@click.option("--latent_dim", default=1000, help="AAA")
@click.option("--lr", default=0.0002, help="AAA")
@click.option("--batch_size", default=32, help="AAA")
@click.option("--save_interval", default=1000, help="AAA")
def main(exp_path, data_path, seq_length, latent_dim, lr, batch_size, save_interval):
    gan = GAN(data_path=data_path, seq_length=seq_length, latent_dim=latent_dim, lr=lr)
    gan.train(
        epochs=1000,
        batch_size=batch_size,
        print_interval=10,
        save_interval=save_interval,
        exp_path=exp_path,
    )
    # for i in range(10):
    #     for j in range(4):
    #         gan.generate(j + 1, i + 1)


if __name__ == "__main__":
    main()
